linagora/twake-workplace

registration/package-lock.json
registration/package.json
registration/src/ambient.d.ts
registration/src/lib/components/input/OtpField.svelte

https://github.com/linagora/twake-workplace/assets/6764881/35f3b38b-f09f-4852-8fc3-4508edcd7e0a
https://github.com/linagora/twake-workplace/assets/6764881/73738981-4079-46ab-aaaf-59729ea516c6

feat:#6 add OTP field

---

registration/src/lib/components/otp/PhoneConfirmed.svelte

feat:#6 add confirmation component

---

registration/src/lib/components/input/TelField.svelte
registration/src/lib/i18n/ar.json
registration/src/lib/i18n/en.json
registration/src/lib/i18n/fr.json
registration/src/lib/i18n/ru.json
registration/src/lib/i18n/vi.json

https://github.com/linagora/twake-workplace/assets/6764881/44f69252-9178-4e19-9051-8273af2316d4

#6 phone field search toggle

---

registration/src/lib/components/input/TelField.svelte

✨ Feat:#6 added loading indicator to phone field

---

registration/src/lib/components/forms/steps/CheckPhoneStep.svelte
registration/src/lib/components/input/TelField.svelte
registration/src/lib/i18n/ar.json
registration/src/lib/i18n/en.json
registration/src/lib/i18n/fr.json
registration/src/lib/i18n/ru.json
registration/src/lib/i18n/vi.json
registration/src/store/index.ts

✨ #6 added mobile check step

---

registration/src/lib/components/forms/steps/CheckOTPStep.svelte

✨ Feat: #6 add OTP check success step

---

registration/src/lib/components/landing/AccessSelect.svelte
registration/src/lib/components/landing/Hero.svelte
registration/src/routes/+layout.svelte
registration/src/routes/+page.svelte
registration/tailwind.config.js

💄 Fix: adjusted main screen layout ( #23 )

---

registration/src/routes/health/+server.ts

🩺 Feat: add healthcheck

---

registration/src/routes/api/send-sms/+server.ts

🎨 use Authorization bearer for send SMS API ( #84 )

---

registration/documentation/README.md

changed auth header to use bearer

📝 chore: updated send sms api doc

---

registration/src/routes/+page.server.ts

closes https://github.com/linagora/twake-on-matrix/issues/1626

🐛 fixed not passing directly to registration step when coming from mobile (twake-on-matrix#1626)

---

registration/src/lib/components/landing/MainScreen.svelte
registration/src/lib/i18n/ar.json
registration/src/lib/i18n/en.json
registration/src/lib/i18n/fr.json
registration/src/lib/i18n/ru.json
registration/src/lib/i18n/vi.json

💄remove use company server link (#94)

---

registration/src/lib/components/dispaly/FormHeader.svelte
registration/src/lib/components/landing/AccessSelect.svelte

🐛 updated the sign up tab switch to destination (#97)

---

registration/src/routes/+page.server.ts

🐛 fixed post_login_redirect overriding the registration steps (#98)

---

registration/src/lib/components/buttons/PrimaryButton.svelte
registration/src/lib/components/buttons/SubmitButton.svelte
registration/src/lib/components/forms/LoginForm.svelte
registration/src/lib/components/forms/steps/recovery/OTPStep.svelte
registration/src/lib/components/forms/steps/recovery/PasswordStep.svelte
registration/src/lib/components/forms/steps/recovery/PhoneStep.svelte
registration/src/lib/components/forms/steps/registration/CheckNickNameStep.svelte
registration/src/lib/components/forms/steps/registration/CheckOTPStep.svelte
registration/src/lib/components/forms/steps/registration/CheckPasswordStep.svelte
registration/src/lib/components/forms/steps/registration/CheckPhoneStep.svelte

closes #120 
https://github.com/linagora/twake-workplace/assets/6764881/72223da4-e3e7-43ad-ba85-044c94f2121a

✨ feat: added loading indicator when submitting (#120)

---

registration/src/lib/components/buttons/PrimaryButton.svelte
registration/src/lib/components/buttons/SubmitButton.svelte
registration/src/lib/components/forms/LoginForm.svelte
registration/src/lib/components/forms/steps/recovery/OTPStep.svelte
registration/src/lib/components/forms/steps/recovery/PasswordStep.svelte
registration/src/lib/components/forms/steps/recovery/PhoneStep.svelte
registration/src/lib/components/forms/steps/registration/CheckNickNameStep.svelte
registration/src/lib/components/forms/steps/registration/CheckOTPStep.svelte
registration/src/lib/components/forms/steps/registration/CheckPasswordStep.svelte
registration/src/lib/components/forms/steps/registration/CheckPhoneStep.svelte

✨ updated forms submit UX (#124)

---

registration/src/lib/utils/phone.ts

🐛 updated phone mask dispaly (#22)

---

registration/src/lib/components/input/TelField.svelte

https://github.com/linagora/twake-workplace/assets/6764881/3bfb8bf0-4698-4f11-80c1-f1dbdd223a6f

✨ search by country code in phone field

---

registration/src/routes/+page.server.ts

- fixed phone input not displaying the default country correctly

🐛 format country code to iso2

---

registration/package-lock.json
registration/src/lib/services/auth/index.ts
registration/src/routes/+page.server.ts
registration/src/routes/success/+page.server.ts

✨ added lemonldap session verification

---

registration/src/lib/components/buttons/NavigateBack.svelte

closes #158 
https://github.com/linagora/twake-workplace/assets/6764881/34a95329-ca17-4f8a-b507-1fd5d1b8bd84

💄 fixed  logo position changing when switching tabs ( #158 )

---

registration/src/lib/utils/proxy.ts

- send Streamable request body
- use duplex ( see https://github.com/nodejs/node/issues/46221 )

🎨 Fix proxy not sending synapse  request body

---

registration/src/lib/components/landing/Hero.svelte

- adjust font size
- adjust line height
- adjust spacing

💄 update the Hero style

---

registration/src/lib/components/views/PasswordRecovery.svelte
registration/src/routes/recover-password/+page.svelte

💄 adjust the recovery page layout

---

registration/src/lib/utils/proxy.ts

- check user session and redirect to login if not authorized
- proxy the request instead of a redirect

✨ check user session when proxying authorize requests

---

registration/src/lib/components/user/MobileSuccessInfo.svelte
registration/src/lib/i18n/ar.json
registration/src/lib/i18n/en.json
registration/src/lib/i18n/fr.json
registration/src/lib/i18n/ru.json
registration/src/lib/i18n/vi.json

🔥 remove unused recovery email button (#180)

---

registration/src/lib/utils/username.ts

🎨 adjust nickname validation regex (#151)

---

registration/package-lock.json
registration/package.json
registration/src/lib/components/products/TdriveProduct.svelte
registration/src/lib/components/products/TmailProduct.svelte
registration/src/lib/components/products/TwakeProduct.svelte
registration/src/lib/utils/url.ts

remove matrix intermediate screen when selecting a product from success page (#176)

---

registration/src/lib/components/products/TdriveProduct.svelte
registration/src/lib/components/products/TmailProduct.svelte
registration/src/lib/components/products/TwakeProduct.svelte

🎨 unify mobile and desktop product texts (#184)

---

registration/src/lib/components/user/MobileSuccessInfo.svelte

🐛 display correct matrix id (#181)

---

registration/src/app.d.ts
registration/src/lib/utils/url.ts
registration/src/routes/+page.server.ts
registration/src/routes/success/+page.server.ts
registration/src/routes/success/+page.svelte
registration/src/store/redirect.ts

🎨 cleanup post signup / sign in redirections

---

registration/src/lib/i18n/ar.json
registration/src/lib/i18n/en.json
registration/src/lib/i18n/fr.json
registration/src/lib/i18n/ru.json
registration/src/lib/i18n/vi.json

🌐 updated privacy policy and terms of use links (#204)

---

registration/src/lib/utils/proxy.ts

🎨 proxy logout requests to lemon (#132)

---

registration/src/lib/components/forms/steps/registration/CheckNickNameStep.svelte
registration/src/lib/components/input/TextField.svelte
registration/src/lib/utils/html.ts
registration/src/lib/utils/timeout.ts

https://github.com/linagora/twake-workplace/assets/6764881/be74e96d-5ae4-47f5-8d3a-434fb30e6835
closes #230

✨ validate the nickname when the user stops typing (#230)

---

registration/src/lib/components/input/TelField.svelte

🐛 fix tel input field glitching while fetching country flags (#233)

---

registration/src/lib/components/forms/steps/registration/CheckNickNameStep.svelte

🐛 fix nickname suggestion re-triggering twice (#250)

---

registration/src/lib/components/forms/steps/registration/CheckNickNameStep.svelte
registration/src/store/registration.ts
registration/src/types/index.ts

closes #251 
https://github.com/linagora/twake-workplace/assets/6764881/8270dd03-69e5-4edf-9abe-50eff84bd970

✨ persist user information when switching tabs (#251)
